name: COVID Box

on:
  push:
    branches: [ master, main ]
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Run statistics action
        uses: puf17640/covid-box@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COUNTRY: ${{ secrets.COUNTRY }}
          GIST_ID: ${{ secrets.GIST_ID }}
